# -*- coding: utf-8 -*-
"""RNA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JHweAi3A1v2MsFT_3BMDZNWJChR1bqGZ
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

metros = np.array([0,1,2,3,4,5,6,7], dtype=float)
pulgadas=np.array([0,39.37,78.74,118.11,157.48,196.85,236.22,275.59], dtype=float)

capa = tf.keras.layers.Dense(units=1,input_shape=[1])
modelo = tf.keras.Sequential([capa])

modelo.compile(
    optimizer = tf.keras.optimizers.Adam(0.1),
    loss = 'mean_squared_error'
)

print("Inicio del entrenamiento")
historial = modelo.fit(metros, pulgadas, epochs=4000, verbose=False)
print("RNA Entrenada")

plt.xlabel("Época")
plt.ylabel("Magnitud de pérdida")
plt.plot(historial.history["loss"])

print("Predicción")
resultado = modelo.predict([10.0])
print("El resultado es: "+str(resultado)+" pulgadas")

"""Exportación"""

#Exportar el modelo en formato h5
modelo.save('metros_a_pulgadas.h5')